resources:
- name: concourse-java
  type: git
  source:
    uri: https://github.com/scarrigan/concourse-java.git
    branch: master
    private_key: {{private-repo-key}}

jobs:
- name: build-app
  plan:
  - get: concourse-java
    trigger: true
  - task: package
    file: concourse-java/ci/package-app.yml
  - task: build-image
    file: greeter-app/ci/build-image.yml