resources:
- name: concourse-java
  type: git
  source:
    uri: https://github.com/scarrigan/concourse-java.git
    branch: master
    private_key: {{private-repo-key}}

- name: docker-image-repo
  type: docker-image
  source:
    repository: scarrigan/greeter-app
    username: scarrigan
    password: {{docker-repo-pwd}}

jobs:
- name: build-app
  plan:
  - get: concourse-java
    trigger: true
  - task: package
    file: concourse-java/ci/package-app.yml
  - put: docker-image-repo
    params: {build: concourse-java}